name: ui_kit
description: UI Kit My Movie Hub
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: google_fonts/Nunito-Black.ttf
          weight: 900
        - asset: google_fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: google_fonts/Nunito-Bold.ttf
          weight: 700
        - asset: google_fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: google_fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: google_fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: google_fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: google_fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: google_fonts/Nunito-Italic.ttf
          style: italic
        - asset: google_fonts/Nunito-Light.ttf
          weight: 300
        - asset: google_fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: google_fonts/Nunito-Medium.ttf
          weight: 500
        - asset: google_fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: google_fonts/Nunito-Regular.ttf
          weight: 400
        - asset: google_fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: google_fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
