name: ui_kit_storybook
description: UI Kit Storybook My Movie Hub
publish_to: none 
version: 1.0.0+1 

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ../ui_kit
  storybook_flutter: 0.14.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
