name: my_movie_hub
description: My Movie Hub App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: 3.16.2

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ../ui/ui_kit
  bloc: ^8.1.2
  dio: 5.4.0
  flutter_bloc: ^8.1.3
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  google_fonts: 6.1.0
  get_it: 7.6.4
  flutter_localizations:
    sdk: flutter
  go_router: 13.0.0
  shared_preferences: 2.2.2
  device_preview: 1.1.0
  easy_localization: ^3.0.3
  multiple_result: 5.1.0
  formz: 0.6.1
  event_bus: 2.0.0
  card_swiper: 3.0.1
  url_launcher: 6.2.5
  shimmer: 3.0.0
  meta: ^1.10.0
  country_code_picker: 3.0.0
  dio_cache_interceptor: 3.5.0
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.10
  flutter_dotenv: 5.1.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: 2.4.7
  flutter_test:
    sdk: flutter
  freezed: 2.4.5
  json_serializable: 6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  #generate: false
  assets:
    - assets/l10n/
    - assets/pngs/
    - assets/google_fonts/
    - .env

flutter_native_splash:
  android: true
  ios: true
  
  color: "#121212"
  image: assets/splash_screen/splash_screen.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  image_path_ios: "assets/launcher_icon/ios_launcher_icon.jpg"
  image_path_android: "assets/launcher_icon/android_launcher_icon.png"
  adaptive_icon_background: "#0D253F"
  adaptive_icon_foreground: "assets/launcher_icon/android_launcher_icon_foreground.png"
  min_sdk_android: 21
