name: my_movie_hub
description: My Movie Hub App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: 3.32.1

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ../ui/ui_kit
  bloc: ^9.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  json_annotation: 4.9.0
  freezed_annotation: ^2.4.4
  google_fonts: 6.1.0
  get_it: ^8.0.3
  flutter_localizations:
    sdk: flutter
  go_router: ^15.1.2
  shared_preferences: 2.5.3
  device_preview: 1.2.0
  easy_localization: ^3.0.3
  multiple_result: ^5.2.0
  formz: ^0.8.0
  event_bus: ^2.0.1
  card_swiper: 3.0.1
  url_launcher: ^6.3.1
  shimmer: 3.0.0
  meta: ^1.10.0
  country_code_picker: ^3.3.0
  dio_cache_interceptor: ^4.0.3
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.10
  flutter_dotenv: 5.2.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  json_serializable: 6.9.5
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  #generate: false
  assets:
    - assets/l10n/
    - assets/pngs/
    - assets/google_fonts/
    - .env

flutter_native_splash:
  android: true
  ios: true
  
  color: "#121212"
  image: assets/splash_screen/splash_screen.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "launcher_icon"
  image_path_ios: "assets/launcher_icon/ios_launcher_icon.jpg"
  image_path_android: "assets/launcher_icon/android_launcher_icon.png"
  adaptive_icon_background: "#0D253F"
  adaptive_icon_foreground: "assets/launcher_icon/android_launcher_icon_foreground.png"
  min_sdk_android: 21