name: my_movie_hub
description: My Movie Hub App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: 3.16.2

dependencies:
  flutter:
    sdk: flutter
  ui_kit:
    path: ../ui/ui_kit
  bloc: ^8.1.2
  dio: 5.4.0
  flutter_bloc: ^8.1.3
  json_annotation: 4.8.1
  freezed_annotation: 2.4.1
  google_fonts: 6.1.0
  get_it: 7.6.4
  flutter_localizations:
    sdk: flutter
  go_router: 13.0.0
  shared_preferences: 2.2.2
  device_preview: 1.1.0
  easy_localization: ^3.0.3
  multiple_result: ^5.1.0
  formz: ^0.6.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: 2.4.7
  flutter_test:
    sdk: flutter
  freezed: 2.4.5
  json_serializable: 6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/l10n/
